(()=>{"use strict";
let home=null,next=null,box=null,launcher=null,overlay=null;
const icon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M9 10h30v22H21l-8 7v-7H9Z" stroke="#fff" stroke-width="2.4"/><circle cx="18" cy="21" r="1.7" fill="#fff"/><circle cx="24" cy="21" r="1.7" fill="#169BFF"/><circle cx="30" cy="21" r="1.7" fill="#fff"/></svg>';
function close(){if(!overlay)return;overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');if(box&&home){box.hidden=true;if(next&&next.parentNode===home)home.insertBefore(box,next);else home.appendChild(box)}document.body.style.overflow='';launcher?.focus({preventScroll:true})}
function ensureOverlay(){if(overlay)return;overlay=document.createElement('div');overlay.className='sss-feedback-overlay';overlay.setAttribute('aria-hidden','true');overlay.innerHTML='<div class="sss-feedback-dialog" role="dialog" aria-modal="true" aria-labelledby="sssFeedbackTitle"><div class="sss-feedback-head"><div class="sss-feedback-title-wrap"><span class="sss-approved-icon-slot">'+icon+'</span><h2 id="sssFeedbackTitle">FEEDBACK</h2></div><button type="button" class="sss-feedback-close" aria-label="Close feedback">×</button></div><div class="sss-feedback-host"></div></div>';document.body.appendChild(overlay);overlay.querySelector('.sss-feedback-close').onclick=close;overlay.onmousedown=e=>{if(e.target===overlay)close()}}
function open(){if(!box)return;ensureOverlay();box.hidden=false;overlay.querySelector('.sss-feedback-host').appendChild(box);overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';requestAnimationFrame(()=>overlay.querySelector('.sss-feedback-close')?.focus({preventScroll:true}))}
function connect(){box=document.getElementById('cvTechnicalFeedback');if(!box)return false;if(box.dataset.popupReady==='1')return true;box.dataset.popupReady='1';home=box.parentNode;next=box.nextSibling;launcher=document.createElement('button');launcher.type='button';launcher.className='sss-feedback-launcher';launcher.textContent='LEAVE FEEDBACK →';launcher.onclick=open;home.insertBefore(launcher,box);box.hidden=true;window.SSSOpenFeedback=open;if(new URLSearchParams(location.search).get('open')==='feedback')open();return true}
if(!connect()){const observer=new MutationObserver(()=>{if(connect())observer.disconnect()});observer.observe(document.body,{childList:true,subtree:true})}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&overlay?.classList.contains('open')){e.preventDefault();close()}});
})();
